env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: "scripts/**"
    rules:
      "@typescript-eslint/no-var-requires": 0
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style: 0
  quotes:
    - error
    - single
  semi:
    - error
    - always
