name: Deploy on production server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy production build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [21.x]

    steps:
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm" # Export NVM
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Change directory to project directory
            cd mcdata-api
